// Package docs exposes the OpenAPI document that protoc-gen-openapiv2
// generates from the proto contract. The file is regenerated by
// scripts/gen_proto.ps1 and embedded into the binary so that the service
// serves its own Swagger documentation without external files.
package docs

import _ "embed"

// SwaggerJSON is the Swagger 2.0 specification of loan.v1.LoanService.
//
//go:embed loan/v1/loan.swagger.json
var SwaggerJSON []byte
